profile: test-2.0

server:
  port: 8681

# actuator management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# actuator info
info:
  app:
    encoding:UTF-8
    java.source:1.8
    java.traget:1.8
    name:provider1


spring:
  application:
    name: first-service-provider-dev
eureka:
  client:
    service-url:
      defaultZone: http://cloudServerSlave1:8780/eureka/,http://cloudServerSlave2:8781/eureka/
  instance:
    prefer-ip-address: true